name: Build macOS

on:
  workflow_dispatch: 

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' 

      - name: Installation des dependances
        run: npm install

      - name: Compilation Apple Silicon (Puces M)
        run: npm run make -- --platform=darwin --arch=arm64

      - name: Compilation Intel (Anciens Mac)
        run: npm run make -- --platform=darwin --arch=x64

      - name: Sauvegarde des fichiers generes
        uses: actions/upload-artifact@v4
        with:
          name: CladisTree-macOS-Complet
          path: out/make/**/*.zip
