name: Build macOS

on:
  workflow_dispatch: 

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' 

      - name: Installation des dependances
        run: npm install

      - name: Compilation de l'application
        run: npm run make

      - name: Sauvegarde du fichier genere
        uses: actions/upload-artifact@v4
        with:
          name: CladisTree-macOS
          path: out/make/**/*.zip
